### ISSUE TITLE
Que datos puedo tener montando este docker para SENASA ..?

### ISSUE THREAD

**Issue by EOM** [Mikroways/ckan-senasa-docker#1]
Hola una consulta, en si que datos puedo tener montando este docker para SENASA ..? Yo porque estoy trabajando con el webserver de ellos online para los PT/PTR autorizaciones sanitarias y quiero ver si tengo alguna ventaja con esto, para DEV y PRODUCCIÓN.

**Comment by chrodriguez** [comment]
Hola, esa consulta deberías hacerla en la DTI de senasa. Desconocemos nosotros el estado de implementación actual de ckan
